#!/usr/bin/env python3
"""Generate the upstream `_target_ratios` lookup table as Rust source.

Run from the lfm crate root and pipe to src/preproc/target_ratios.rs:
    python3 scripts/derive_target_ratios.py > src/preproc/target_ratios.rs

Why a static table instead of computing in Rust? Upstream's
`_target_ratios(min_tiles, max_tiles)` returns
`sorted(set(ratios), key=product)`. The `set(...)` step's iteration
order is hash-dependent (CPython implementation detail), which then
becomes an order-sensitive input to `find_closest_aspect_ratio`'s
tie-break (`if ratio_diff == best_ratio_diff: ...`). For equal-product
equal-diff candidates, upstream's choice depends on whether the
"squarest" candidate happens to land first or last in Python's set
iteration order — and there's no closed-form Rust equivalent that
matches CPython's hash-based ordering bit-for-bit. The pragmatic fix is
to emit Python's actual order at build time and embed it.
"""


def target_ratios(min_t: int, max_t: int) -> list[tuple[int, int]]:
    rs = [
        (w, h)
        for n in range(min_t, max_t + 1)
        for w in range(1, n + 1)
        for h in range(1, n + 1)
        if min_t <= w * h <= max_t
    ]
    return sorted(set(rs), key=lambda x: x[0] * x[1])


def main() -> None:
    print("// AUTO-GENERATED by scripts/derive_target_ratios.py — do not edit by hand.")
    print("// Mirrors upstream _target_ratios from")
    print("// transformers/models/lfm2_vl/image_processing_lfm2_vl_fast.py:231-239")
    print("// (the sorted(set(ratios), key=product) result, which depends on CPython")
    print("// set iteration order — must be replicated bit-for-bit for tie-break parity).")
    print()
    print("/// Upstream-Python `_target_ratios(min_tiles, max_tiles)` lookup.")
    print("///")
    print("/// Returns the candidate `(cols, rows)` list in the exact order CPython's")
    print("/// `sorted(set(ratios), key=product)` produces — required so")
    print("/// [`find_closest_aspect_ratio`]'s tie-break (which is iteration-order")
    print("/// sensitive on equal-product equal-diff candidates) matches upstream's")
    print("/// behavior bit-for-bit.")
    print("///")
    print("/// `(min_tiles, max_tiles)` outside `[1, MAX_TOKENIZER_TILE_DIM]` returns")
    print("/// an empty slice; `ImageBudget::validate()` already rejects those budgets")
    print("/// at construction-time.")
    print("pub(crate) fn target_ratios(min_tiles: u32, max_tiles: u32) -> &'static [(u32, u32)] {")
    print("  match (min_tiles, max_tiles) {")
    for mn in range(1, 11):
        for mx in range(mn, 11):
            rs = target_ratios(mn, mx)
            rs_str = ", ".join(f"({a},{b})" for a, b in rs)
            print(f"    ({mn}, {mx}) => &[{rs_str}],")
    print("    _ => &[],  // Outside [1, MAX_TOKENIZER_TILE_DIM]; rejected at construction.")
    print("  }")
    print("}")


if __name__ == "__main__":
    main()
